apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubernetes-pipeline 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-pipeline
  template:
    metadata:
      labels:
        app: kubernetes-pipeline 
    spec:
      containers:
        - name: kubernetes-pipeline 
          image: onlyregistryhere.azurecr.io/kubernetes-pipeline
          ports:
          - containerPort: 7000