apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubernetespipeline 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetespipeline
  template:
    metadata:
      labels:
        app: kubernetespipeline 
    spec:
      containers:
        - name: kubernetespipeline 
          image: onlyregistryhere.azurecr.io/kubernetespipeline
          ports:
          - containerPort: 3000